<html>
<head>
	<title>Catalysis Events</title>

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">

	<!-- Optional theme -->
	<link rel="stylesheet" href="bootstrap/css/bootstrap-theme.min.css">

	<!-- Main Style -->
	<link rel="stylesheet" href="css/style.css">

	<link href='https://fonts.googleapis.com/css?family=Lato:400,700,300' rel='stylesheet' type='text/css'>

	<!-- Jquery -->
	<script src="bootstrap/js/jquery.min.js"></script>

	<!-- Latest compiled and minified JavaScript -->
	<script src="bootstrap/js/bootstrap.min.js"></script>
</head>
<body>
	<header>
		<div class="logo"></div>
		<nav>
			
		</nav>
	</header>
	<section class="slider">

	</section>
	<section class="container">

		<h3>
			<div class="title-back" ><span></span></div>
			<div class="title">Services & Produits</div>
		</h3>

		<?php echo $this->layout()->content; ?>	
	</section>
	<footer>

	</footer>

</body>
</html>

